# Generated by Django 3.0.8 on 2020-08-02 19:57

from django.db import migrations, models
import django.db.models.deletion
from django.core.management import call_command


def load_initial_data(apps, schema_editor):
    # Учитываем порядок файлов импорта
    call_command('loaddata', 'Contact.json')
    call_command('loaddata', 'ProductCategory.json')
    call_command('loaddata', 'Product.json')


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200, verbose_name='город')),
                ('phone', models.CharField(max_length=20, verbose_name='телефон')),
                ('email', models.CharField(max_length=100, verbose_name='email')),
                ('address', models.CharField(max_length=300, verbose_name='адрес')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='категория товара')),
                ('desc', models.TextField(blank=True, verbose_name='описание категории')),
                ('href', models.CharField(max_length=30, verbose_name='internal href')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='имя продукта')),
                ('desc', models.TextField(blank=True, verbose_name='описание продукта')),
                ('short_desc', models.CharField(blank=True, max_length=200, verbose_name='краткое описание продукта')),
                ('img_src', models.ImageField(blank=True, upload_to='products_img')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='стоимость продукта')),
                ('quantity', models.IntegerField(default=0, verbose_name='количество единиц продукта')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.ProductCategory')),
            ],
        ),

        migrations.RunPython(load_initial_data),
    ]
